name: habesha_dating_app
description: A dating app connecting the global Habesha diaspora with Ethiopia-based users.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Database & Backend
  supabase_flutter: ^2.0.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  
  # UI & Theming
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Media & Camera
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  just_audio: ^0.9.36
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  uuid: ^4.2.1
  
  # Payments (will be added later)
  # in_app_purchase: ^3.1.11
  
  # Video Calls (will be added later)
  # agora_rtc_engine: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.3
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Fonts (will be configured with Google Fonts)
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
